#
/*
 * config.c (config.proto)
 *
 * Copyright (c) 1985 Adobe Systems Incorporated
 *
 * defines global string constants for default directories
 * config.c is generated by the Makefile doing a "sed" on config.proto
 *
 * RCSID: $Header: /group/lattice/cvsroot/axis/config.c,v 1.1 2006/06/03 19:34:25 edwards Exp $
 *
 * Edit History:
 * Andrew Shore: Tue May 14 10:12:14 1985
 * End Edit History.
 *
 * RCSLOG:
 * $Log: config.c,v $
 * Revision 1.1  2006/06/03 19:34:25  edwards
 * Initial version.
 *
 * Revision 2.1  85/11/24  11:48:50  shore
 * Product Release 2.0
 * 
 * Revision 1.3  85/11/20  00:01:25  shore
 * Removed some printer-specific things to shell interface/environment
 * for Release 2.0
 * 
 * Revision 1.2  85/05/14  11:21:11  shore
 * 
 * 
 *
 */

/* note the trailing / on TroffFontDir are important here */
char LibDir[]	= "/usr/local/lib/ps";
char TroffFontDir[] = "/usr/local/lib/troff.font/";
char DitDir[]	= "/usr/local/lib/font";
char TempDir[]	= "/usr/tmp";
